version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: backtrader_timescaledb
    environment:
      POSTGRES_DB: backtrader
      POSTGRES_USER: backtrader_user
      POSTGRES_PASSWORD: backtrader_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: [
      "postgres",
      "-c", "max_locks_per_transaction=256",
      "-c", "shared_buffers=256MB",
      "-c", "work_mem=4MB",
      "-c", "maintenance_work_mem=64MB"
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backtrader_user -d backtrader"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: backtrader_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@backtrader.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - timescaledb
    restart: unless-stopped
